### ISSUE TITLE
Add option to disable postgresql service from starting.

### ISSUE THREAD

**Issue by wojtek-oledzki** [sansible/postgresql#7]
**As a** Ops
**I want to** choose if postgresql service should be running after including this role
**So that** I don't have to hack it when building using "chroot"

**Comment by dennisconrad** [comment]
Do you want to prevent PostgreSQL from starting _at all_ after installation, or is it enough to stop the service after it has been started, and prevent it from coming up automatically at boot?  The latter is easy to achieve, the other... not so easy.
